export const PRODUCT_TYPE_SHIPPING = "UHJvZHVjdFR5cGU6MTY=";
export const PRODUCT_TYPE_ONLINE_ZAHIALGA = "UHJvZHVjdFR5cGU6MTU=";
export const PRODUCT_CATEGORY_SHIPPING = "Q2F0ZWdvcnk6MjQ=";
export const PRODUCT_CATEGORY_ONLINE_ZAHIALGA = "Q2F0ZWdvcnk6MjM=";

/** ene asia shuu  */
export const WAREHOUSE_ASIA =
  "V2FyZWhvdXNlOjQ4ZjU5YjRmLWMxODUtNGUzMi05MjExLTMzOWE5NGJlYmIxYw==";
